{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idr-enterprise.fullname" . }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "idr-enterprise.name" . }}
      app.kubernetes.io/component: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "idr-enterprise.name" . }}
        app.kubernetes.io/component: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args:
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "idr-enterprise.secretName" . }}
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import/idr-realm.json
              subPath: idr-realm.json
      volumes:
        - name: realm
          configMap:
            name: {{ include "idr-enterprise.fullname" . }}-keycloak-realm
{{- end }}
