apiVersion: v1
kind: Service
metadata:
  name: {{ include "idr-enterprise.fullname" . }}-ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "idr-enterprise.name" . }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: 80
