import argparse
import os
import sys

# Add project root to path to import idr_core
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from idr_core.config import config_to_sql, load_config


def main():
    parser = argparse.ArgumentParser(description="Generate IDR SQL setup from YAML config")
    parser.add_argument("--config", required=True, help="Path to YAML config file")
    parser.add_argument("--output", required=True, help="Output SQL file path")
    parser.add_argument(
        "--platform",
        default="duckdb",
        choices=["duckdb", "snowflake", "bigquery", "databricks"],
        help="Target platform dialect (default: duckdb)",
    )

    args = parser.parse_args()

    try:
        config = load_config(args.config)
        statements = config_to_sql(config, dialect=args.platform)

        with open(args.output, "w") as f:
            f.write("-- ============================================================\n")
            f.write(f"-- Generated by tools/generate_config.py for {args.platform.upper()}\n")
            f.write("-- Do not edit manually. Update the YAML config instead.\n")
            f.write("-- ============================================================\n\n")

            # Write statements
            for stmt in statements:
                f.write(stmt)
                f.write(";\n")

        print(f"Generated SQL written to {args.output}")

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
